server:
  servlet:
    context-path: "/api/v1"
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: dev
#  datasource:
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        default_schema: core
    generate-ddl: true
#    show-sql: true

app:
  general :
    basePackage : com.ownqr
    api :
      version : 1
