spring:
  profiles:
    active: local
    include: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/core?createDatabaseIfNotExist=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
#    url : jdbc:h2:mem:ccore
    username: ayeremeiev
