server:
  servlet:
    context-path: "/api/v1"
  error:
    whitelabel:
      enabled: false

flyway:


spring:
  profiles:
    active: dev
#  datasource:
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target : create.sql
              create-source : metadata
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: core
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#  flyway:
#    baseline-on-migrate: true
#    show-sql: true

app:
  general :
    basePackage : com.ownqr
    api :
      version : 1
